from __future__ import annotations

import unittest

from ida_pseudoforge.core.plan_schema import CleanPlan, CleanupLabel, FlowRewrite, FunctionCapture, RenameSuggestion
from ida_pseudoforge.core.render_header import kernel_semantic_rewrite_count, render_header_lines


def _plan() -> CleanPlan:
    plan = CleanPlan(
        function_ea=0x140001000,
        function_name="Sample",
        input_fingerprint="fp",
    )
    plan.renames.append(RenameSuggestion("lvar", "a1", "argument0", 0.82, "prototype", "fixture"))
    plan.flow_rewrites.append(FlowRewrite(kind="switch", dispatcher="code", recovered_cases=[1, 2], confidence=0.91))
    plan.comments.append({"kind": "critical_region", "text": "한글 insight", "confidence": 0.9})
    plan.cleanup_labels.append(
        CleanupLabel(
            label="LABEL_1",
            classification="release_resource_and_leave_critical_region",
            start_line=10,
            end_line=12,
            confidence=0.88,
            evidence="cleanup tail",
        )
    )
    return plan


class RenderHeaderTests(unittest.TestCase):
    def test_render_header_lines_includes_flow_comments_labels_warnings_and_renames(self) -> None:
        plan = _plan()
        capture = FunctionCapture(ea=0x140001000, name="Sample", pseudocode="")

        header = "\n".join(
            render_header_lines(
                capture,
                plan,
                {"a1": "argument0"},
                ["manual warning"],
                {"code"},
                "0.1.0",
            )
        )

        self.assertIn("Generated by PseudoForge.", header)
        self.assertIn("Kernel semantic rewrites: 2", header)
        self.assertIn("Flow: switch dispatcher=code cases=[1, 2] confidence=0.91 source=native_switch", header)
        self.assertIn("\\ud55c\\uae00 insight", header)
        self.assertIn("Label roles:", header)
        self.assertIn("Warning detail:", header)
        self.assertIn("Renames: a1->argument0(0.82,prototype)", header)

    def test_kernel_semantic_rewrite_count_counts_known_comments_and_labels(self) -> None:
        self.assertEqual(kernel_semantic_rewrite_count(_plan()), 2)


if __name__ == "__main__":
    unittest.main()
