from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any

from ida_pseudoforge.profiles.loader import load_json_profile, load_kernel_api_family


_CUSTOM_FLAG_ENUMS: dict[str, dict[str, str]] = {
    "FILE_DEVICE_CHARACTERISTICS": {
        "1": "FILE_REMOVABLE_MEDIA",
        "2": "FILE_READ_ONLY_DEVICE",
        "4": "FILE_FLOPPY_DISKETTE",
        "8": "FILE_WRITE_ONCE_MEDIA",
        "16": "FILE_REMOTE_DEVICE",
        "32": "FILE_DEVICE_IS_MOUNTED",
        "64": "FILE_VIRTUAL_VOLUME",
        "128": "FILE_AUTOGENERATED_DEVICE_NAME",
        "256": "FILE_DEVICE_SECURE_OPEN",
        "2048": "FILE_CHARACTERISTIC_PNP_DEVICE",
        "4096": "FILE_CHARACTERISTIC_TS_DEVICE",
        "8192": "FILE_CHARACTERISTIC_WEBDAV_DEVICE",
        "16384": "FILE_PORTABLE_DEVICE",
        "131072": "FILE_DEVICE_ALLOW_APPCONTAINER_TRAVERSAL",
    },
    "MM_COPY_MEMORY_FLAGS": {
        "1": "MM_COPY_MEMORY_PHYSICAL",
        "2": "MM_COPY_MEMORY_VIRTUAL",
    },
}


@dataclass(frozen=True)
class _ResolvedIndirectCall:
    variable: str
    function_name: str
    confidence: float
    evidence: str


def lookup_kernel_symbol(name: str) -> list[dict[str, Any]]:
    symbols = _kernel_symbols()
    if not isinstance(symbols, dict):
        return []
    entries = symbols.get(name, [])
    if not isinstance(entries, list):
        return []
    result = [entry for entry in entries if isinstance(entry, dict)]
    if result:
        return result
    functions = _kernel_functions()
    alias = _resolve_function_alias(name, functions)
    if alias is None:
        return []
    target_name, alias_kind = alias
    target = functions.get(target_name, {})
    entry: dict[str, Any] = {
        "kind": "function_alias",
        "name": name,
        "target": target_name,
        "alias_kind": alias_kind,
    }
    if isinstance(target, dict):
        header = str(target.get("header", ""))
        if header:
            entry["header"] = header
    return [entry]


def kernel_function_metadata(name: str) -> dict[str, Any]:
    return _function_metadata_for_name(_kernel_functions(), name)


def apply_kernel_api_rewrites(text: str) -> str:
    functions = _kernel_functions()
    if not isinstance(functions, dict) or not functions:
        return text

    profile = _kernel_api_rewrite_profile(functions)
    result = text
    rewrite_names = _rewrite_function_names(profile, functions, result)
    for function_name in rewrite_names:
        metadata = _function_metadata_for_name(functions, function_name)
        if not metadata:
            continue
        result = _rewrite_function_calls(result, function_name, metadata, profile)
    result = _rewrite_resolved_indirect_function_calls(result, profile, functions)
    return result


def kernel_api_prelude(text: str) -> str:
    if "POOL_TAG(" not in text:
        return ""
    return "\n".join(
        [
            "#ifndef PSEUDOFORGE_POOL_TAG",
            "#define PSEUDOFORGE_POOL_TAG(a, b, c, d) ((ULONG)(a) | ((ULONG)(b) << 8) | ((ULONG)(c) << 16) | ((ULONG)(d) << 24))",
            "#endif",
            "#ifndef POOL_TAG",
            "#define POOL_TAG(a, b, c, d) PSEUDOFORGE_POOL_TAG(a, b, c, d)",
            "#endif",
            "",
        ]
    )


def decode_pool_tag_literal(literal: str) -> str:
    value = _parse_numeric_literal(literal)
    if value is None:
        return ""
    value &= 0xFFFFFFFF
    chars = []
    for shift in (0, 8, 16, 24):
        byte = (value >> shift) & 0xFF
        if byte < 0x20 or byte > 0x7E:
            return ""
        char = chr(byte)
        if char in {"'", "\\"}:
            return ""
        chars.append(char)
    return "".join(chars)


def _kernel_api_profile() -> dict[str, Any]:
    profile = {
        "functions": _kernel_functions(),
        "enums": _kernel_enums(),
        "structures": _kernel_structures(),
        "aliases": _kernel_aliases(),
        "macros": _kernel_macros(),
        "symbols": _kernel_symbols(),
        "indices": _kernel_indices(),
    }
    return profile if any(profile.values()) else {}


def _kernel_api_overrides() -> dict[str, Any]:
    data = load_json_profile("kernel_api_overrides.json")
    return data if isinstance(data, dict) else {}


def _kernel_api_rewrite_profile(functions: dict[str, Any]) -> dict[str, Any]:
    return {
        "functions": functions,
        "enums": _kernel_enums(),
        "indices": _kernel_indices(),
    }


def _kernel_functions(profile: dict[str, Any] | None = None) -> dict[str, Any]:
    functions = load_kernel_api_family("functions") if profile is None else profile.get("functions", {})
    return functions if isinstance(functions, dict) else {}


def _kernel_enums() -> dict[str, Any]:
    enums = load_kernel_api_family("enums")
    return enums if isinstance(enums, dict) else {}


def _kernel_structures() -> dict[str, Any]:
    structures = load_kernel_api_family("structures")
    return structures if isinstance(structures, dict) else {}


def _kernel_aliases() -> dict[str, Any]:
    aliases = load_kernel_api_family("aliases")
    return aliases if isinstance(aliases, dict) else {}


def _kernel_macros() -> dict[str, Any]:
    macros = load_kernel_api_family("macros")
    return macros if isinstance(macros, dict) else {}


def _kernel_symbols() -> dict[str, Any]:
    symbols = load_kernel_api_family("symbols")
    return symbols if isinstance(symbols, dict) else {}


def _kernel_indices() -> dict[str, Any]:
    indices = load_kernel_api_family("indices")
    return indices if isinstance(indices, dict) else {}


def _function_metadata_for_name(functions: dict[str, Any], name: str) -> dict[str, Any]:
    direct = functions.get(name)
    if isinstance(direct, dict):
        return _apply_function_metadata_overrides(name, direct)

    alias = _resolve_function_alias(name, functions)
    if alias is None:
        return {}
    target_name, alias_kind = alias
    target = functions.get(target_name, {})
    if not isinstance(target, dict):
        return {}
    return _apply_function_metadata_overrides(target_name, target, name, alias_kind)


def _resolve_function_alias(name: str, functions: dict[str, Any]) -> tuple[str, str] | None:
    overrides = _kernel_api_overrides()
    aliases = overrides.get("function_aliases", {})
    if isinstance(aliases, dict):
        target = aliases.get(name)
        if isinstance(target, str) and target in functions:
            return target, "explicit"

    rules = overrides.get("prefix_alias_rules", [])
    if not isinstance(rules, list):
        return None
    for rule in rules:
        if not isinstance(rule, dict):
            continue
        private_prefix = str(rule.get("private_prefix", ""))
        public_prefix = str(rule.get("public_prefix", ""))
        if not private_prefix or not public_prefix or not name.startswith(private_prefix):
            continue
        target = public_prefix + name[len(private_prefix) :]
        if target in functions:
            return target, "prefix_rule"
    return None


def _apply_function_metadata_overrides(
    function_name: str,
    metadata: dict[str, Any],
    alias_name: str = "",
    alias_kind: str = "",
) -> dict[str, Any]:
    result = dict(metadata)
    params = []
    source_params = metadata.get("params", [])
    if isinstance(source_params, list):
        for param in source_params:
            params.append(dict(param) if isinstance(param, dict) else param)
    result["params"] = params

    if alias_name:
        result["profile_alias_of"] = function_name
        result["profile_alias_kind"] = alias_kind

    _apply_parameter_overrides(function_name, params)
    if alias_name:
        _apply_parameter_overrides(alias_name, params)
    _apply_inferred_parameter_kinds(function_name, params)
    return result


def _apply_parameter_overrides(function_name: str, params: list[Any]) -> None:
    overrides = _kernel_api_overrides().get("parameter_overrides", {})
    if not isinstance(overrides, dict):
        return
    function_overrides = overrides.get(function_name, {})
    if not isinstance(function_overrides, dict):
        return
    for index_text, override in function_overrides.items():
        if not isinstance(override, dict):
            continue
        try:
            index = int(str(index_text), 0)
        except ValueError:
            continue
        if index < 0 or index >= len(params) or not isinstance(params[index], dict):
            continue
        params[index].update(override)


def _apply_inferred_parameter_kinds(function_name: str, params: list[Any]) -> None:
    for param in params:
        if not isinstance(param, dict) or param.get("kind") != "value":
            continue
        inferred_kind = _infer_parameter_kind(function_name, param)
        if not inferred_kind:
            continue
        param["kind"] = inferred_kind
        if inferred_kind == "bool":
            param["enum"] = "BOOLEAN"


def _infer_parameter_kind(function_name: str, param: dict[str, Any]) -> str:
    param_name = str(param.get("name", "")).strip()
    param_type = str(param.get("type", "")).upper()
    normalized_type = re.sub(r"\b(IN|OUT|OPTIONAL|CONST)\b", " ", param_type)
    normalized_type = re.sub(r"\s+", " ", normalized_type).strip()
    if param_name == "Tag" and "ULONG" in normalized_type:
        lowered_name = function_name.lower()
        if "withtag" in lowered_name or "pool" in lowered_name or "lookaside" in lowered_name:
            return "pool_tag"
    if re.fullmatch(r"(?:_LITERAL_ )?BOOLEAN", normalized_type):
        return "bool"
    return ""


def _rewrite_function_calls(text: str, function_name: str, metadata: dict[str, Any], profile: dict[str, Any]) -> str:
    result = []
    index = 0
    pattern = re.compile(r"\b%s\s*\(" % re.escape(function_name))
    while True:
        match = pattern.search(text, index)
        if match is None:
            result.append(text[index:])
            break

        open_index = text.find("(", match.start())
        close_index = _find_matching_parenthesis(text, open_index)
        if close_index < 0:
            result.append(text[index:])
            break

        result.append(text[index : match.start()])
        original_args = text[open_index + 1 : close_index]
        rewritten_args = _rewrite_arguments(original_args, metadata, profile)
        result.append(function_name)
        result.append("(")
        result.append(rewritten_args)
        result.append(")")
        index = close_index + 1
    return "".join(result)


def _rewrite_resolved_indirect_function_calls(
    text: str,
    profile: dict[str, Any],
    functions: dict[str, Any],
) -> str:
    resolved_calls = _resolved_indirect_call_map(text, functions)
    if not resolved_calls:
        return text

    result = []
    index = 0
    name_pattern = "|".join(re.escape(name) for name in sorted(resolved_calls, key=len, reverse=True))
    pattern = re.compile(r"\b(?P<name>%s)\s*\(" % name_pattern)

    while True:
        match = pattern.search(text, index)
        if match is None:
            result.append(text[index:])
            break

        resolved = resolved_calls.get(match.group("name"))
        if resolved is None:
            result.append(text[index : match.end()])
            index = match.end()
            continue

        open_index = text.find("(", match.start())
        close_index = _find_matching_parenthesis(text, open_index)
        if close_index < 0:
            result.append(text[index:])
            break

        metadata = _function_metadata_for_name(functions, resolved.function_name)
        if not metadata or not _call_arity_matches(text[open_index + 1 : close_index], metadata):
            result.append(text[index : match.end()])
            index = match.end()
            continue

        line_start = text.rfind("\n", 0, match.start()) + 1
        if line_start >= index:
            result.append(text[index:line_start])
            if not _previous_line_is_resolved_indirect_comment(text, line_start):
                indent = _leading_whitespace(text[line_start : match.start()])
                result.append(
                    "%s// PseudoForge: resolved indirect call %s as %s via MmGetSystemRoutineAddress "
                    "confidence=%.2f; %s\n"
                    % (
                        indent,
                        resolved.variable,
                        resolved.function_name,
                        resolved.confidence,
                        resolved.evidence,
                    )
                )
            result.append(text[line_start : match.start()])
        else:
            result.append(text[index : match.start()])

        original_args = text[open_index + 1 : close_index]
        rewritten_args = _rewrite_arguments(original_args, metadata, profile)
        result.append(resolved.variable)
        result.append("(")
        result.append(rewritten_args)
        result.append(")")
        index = close_index + 1

    return "".join(result)


def _resolved_indirect_call_map(text: str, functions: dict[str, Any]) -> dict[str, _ResolvedIndirectCall]:
    unicode_routines = _unicode_routine_string_map(text, functions)
    resolved: dict[str, _ResolvedIndirectCall] = {}

    for target, source in _mm_get_system_routine_assignments(text):
        resolved_from_string = unicode_routines.get(source, "")
        resolved_from_variable = _profile_function_name_from_variable(target, functions)

        function_name = ""
        confidence = 0.0
        evidence = ""
        if resolved_from_string:
            function_name = resolved_from_string
            confidence = 0.95
            evidence = 'routine string L"%s"' % resolved_from_string
            if resolved_from_variable and resolved_from_variable != resolved_from_string:
                evidence += " overrides variable-name hint %s" % resolved_from_variable
        elif resolved_from_variable:
            function_name = resolved_from_variable
            confidence = 0.70
            evidence = "inferred from function pointer variable name"

        if not function_name:
            continue
        resolved[target] = _ResolvedIndirectCall(
            variable=target,
            function_name=function_name,
            confidence=confidence,
            evidence=evidence,
        )

    return resolved


def _unicode_routine_string_map(text: str, functions: dict[str, Any]) -> dict[str, str]:
    result: dict[str, str] = {}
    pattern = re.compile(
        r"\b(?:RtlInitUnicodeString|RtlUnicodeStringInit)\s*\(\s*&(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*,\s*"
        r"L\"(?P<routine>[A-Za-z_][A-Za-z0-9_]*)\"\s*\)"
    )
    for match in pattern.finditer(text):
        routine = match.group("routine")
        if _function_metadata_for_name(functions, routine):
            result[match.group("name")] = routine

    constant_pattern = re.compile(
        r"(?m)^\s*(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*RTL_CONSTANT_STRING\s*\(\s*"
        r"L\"(?P<routine>[A-Za-z_][A-Za-z0-9_]*)\"\s*\)\s*;"
    )
    for match in constant_pattern.finditer(text):
        routine = match.group("routine")
        if _function_metadata_for_name(functions, routine):
            result[match.group("name")] = routine
    return result


def _mm_get_system_routine_assignments(text: str) -> list[tuple[str, str]]:
    assignments: list[tuple[str, str]] = []
    for line in text.splitlines():
        if "MmGetSystemRoutineAddress" not in line:
            continue
        lhs = re.match(r"\s*(?P<target>[A-Za-z_][A-Za-z0-9_]*)\s*=", line)
        if lhs is None:
            continue
        call = re.search(r"\bMmGetSystemRoutineAddress\s*\(", line)
        if call is None:
            continue
        open_index = line.find("(", call.start())
        close_index = _find_matching_parenthesis(line, open_index)
        if close_index < 0:
            continue
        argument_text = line[open_index + 1 : close_index]
        identifiers = re.findall(r"\b[A-Za-z_][A-Za-z0-9_]*\b", argument_text)
        if not identifiers:
            continue
        assignments.append((lhs.group("target"), identifiers[-1]))
    return assignments


def _profile_function_name_from_variable(name: str, functions: dict[str, Any]) -> str:
    for candidate in _profile_function_name_candidates(name):
        if _function_metadata_for_name(functions, candidate):
            return candidate
    return ""


def _profile_function_name_candidates(name: str) -> list[str]:
    raw = (name or "").strip()
    if not raw:
        return []

    candidates = [raw]
    normalized = raw.strip("_")
    if normalized and normalized != raw:
        candidates.append(normalized)

    for prefix in ("g_", "s_", "m_", "g", "s", "m"):
        if normalized.startswith(prefix) and len(normalized) > len(prefix):
            stripped = normalized[len(prefix) :]
            if stripped:
                candidates.append(stripped)

    expanded: list[str] = []
    for candidate in candidates:
        expanded.append(candidate)
        if len(candidate) > 2 and candidate[0] == "p" and candidate[1].isupper():
            expanded.append(candidate[1:])
        if len(candidate) > 3 and candidate[:2].lower() == "fn" and candidate[2].isupper():
            expanded.append(candidate[2:])
        for suffix in ("Function", "Routine", "Pointer", "Ptr", "Fn"):
            if candidate.endswith(suffix) and len(candidate) > len(suffix):
                expanded.append(candidate[: -len(suffix)])

    return _dedupe_names(expanded)


def _call_arity_matches(argument_text: str, metadata: dict[str, Any]) -> bool:
    arguments = _split_arguments(argument_text)
    params = metadata.get("params", [])
    if not isinstance(params, list):
        return False
    return len(arguments) == len(params)


def _previous_line_is_resolved_indirect_comment(text: str, line_start: int) -> bool:
    previous_end = max(0, line_start - 1)
    previous_start = text.rfind("\n", 0, previous_end) + 1
    previous_line = text[previous_start:previous_end]
    return "PseudoForge: resolved indirect call" in previous_line


def _leading_whitespace(text: str) -> str:
    match = re.match(r"\s*", text)
    return match.group(0) if match is not None else ""


def _has_rewrite_semantics(metadata: dict[str, Any]) -> bool:
    params = metadata.get("params", [])
    if not isinstance(params, list):
        return False
    for param in params:
        if not isinstance(param, dict):
            continue
        if param.get("kind") in {"flags", "pool_tag", "bool"}:
            return True
    return False


def _rewrite_function_names(profile: dict[str, Any], functions: dict[str, Any], text: str) -> list[str]:
    names = []
    indices = profile.get("indices", {})
    if isinstance(indices, dict):
        rewrite_functions = indices.get("rewrite_functions", [])
        if isinstance(rewrite_functions, list):
            names.extend(str(name) for name in rewrite_functions if str(name) in functions)
    names.extend(
        name
        for name, metadata in functions.items()
        if isinstance(metadata, dict) and _has_rewrite_semantics(_function_metadata_for_name(functions, name))
    )
    names.extend(
        name
        for name in _find_call_names(text)
        if _has_rewrite_semantics(_function_metadata_for_name(functions, name))
    )
    return _dedupe_names(names)


def _find_call_names(text: str) -> list[str]:
    return [match.group(1) for match in re.finditer(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*\(", text)]


def _dedupe_names(names: list[str]) -> list[str]:
    result = []
    seen = set()
    for name in names:
        if not name or name in seen:
            continue
        seen.add(name)
        result.append(name)
    return result


def _rewrite_arguments(argument_text: str, metadata: dict[str, Any], profile: dict[str, Any]) -> str:
    arguments = _split_arguments(argument_text)
    params = metadata.get("params", [])
    if not isinstance(params, list):
        return argument_text
    rewritten = []
    changed = False
    for index, argument in enumerate(arguments):
        param = params[index] if index < len(params) and isinstance(params[index], dict) else {}
        updated = _rewrite_argument(argument.strip(), param, profile)
        changed = changed or updated != argument.strip()
        rewritten.append(updated)
    if not changed:
        return argument_text
    return ", ".join(rewritten)


def _rewrite_argument(argument: str, param: dict[str, Any], profile: dict[str, Any]) -> str:
    kind = str(param.get("kind", ""))
    if kind == "flags":
        enum_name = str(param.get("enum", ""))
        return _format_flags(argument, enum_name, profile) or argument
    if kind == "pool_tag":
        return _format_pool_tag(argument) or argument
    if kind == "bool":
        enum_name = str(param.get("enum", "BOOLEAN"))
        return _format_enum_literal(argument, enum_name, profile) or argument
    return argument


def _format_flags(argument: str, enum_name: str, profile: dict[str, Any]) -> str:
    value = _parse_numeric_literal(argument)
    if value is None:
        return ""
    enums = profile.get("enums", {})
    enum_values = enums.get(enum_name, {}) if isinstance(enums, dict) else {}
    if not enum_values:
        enum_values = _CUSTOM_FLAG_ENUMS.get(enum_name, {})
    if not isinstance(enum_values, dict):
        return ""
    remaining = value
    parts = []
    entries = []
    for literal, name in enum_values.items():
        try:
            flag_value = int(str(literal), 0)
        except ValueError:
            continue
        if flag_value <= 0:
            continue
        entries.append((flag_value, str(name)))
    for flag_value, name in sorted(entries, key=lambda item: item[0], reverse=True):
        if (remaining & flag_value) == flag_value:
            parts.append(name)
            remaining &= ~flag_value
    if remaining:
        parts.append("0x%X" % remaining)
    if not parts:
        return "0"
    return " | ".join(reversed(parts))


def _format_pool_tag(argument: str) -> str:
    tag = decode_pool_tag_literal(argument)
    if not tag:
        return ""
    return "POOL_TAG('%s', '%s', '%s', '%s')" % (tag[0], tag[1], tag[2], tag[3])


def _format_enum_literal(argument: str, enum_name: str, profile: dict[str, Any]) -> str:
    value = _parse_numeric_literal(argument)
    if value is None:
        return ""
    enums = profile.get("enums", {})
    enum_values = enums.get(enum_name, {}) if isinstance(enums, dict) else {}
    if not isinstance(enum_values, dict):
        return ""
    return str(enum_values.get(str(value), ""))


def _split_arguments(argument_text: str) -> list[str]:
    arguments = []
    current = []
    depth = 0
    in_string = False
    quote = ""
    index = 0
    while index < len(argument_text):
        char = argument_text[index]
        if in_string:
            current.append(char)
            if char == "\\" and index + 1 < len(argument_text):
                index += 1
                current.append(argument_text[index])
            elif char == quote:
                in_string = False
            index += 1
            continue
        if char in {"'", '"'}:
            in_string = True
            quote = char
            current.append(char)
        elif char == "(":
            depth += 1
            current.append(char)
        elif char == ")":
            depth = max(0, depth - 1)
            current.append(char)
        elif char == "," and depth == 0:
            arguments.append("".join(current).strip())
            current = []
        else:
            current.append(char)
        index += 1
    if current or argument_text.strip():
        arguments.append("".join(current).strip())
    return arguments


def _find_matching_parenthesis(text: str, open_index: int) -> int:
    depth = 0
    in_string = False
    quote = ""
    index = open_index
    while index < len(text):
        char = text[index]
        if in_string:
            if char == "\\":
                index += 2
                continue
            if char == quote:
                in_string = False
            index += 1
            continue
        if char in {"'", '"'}:
            in_string = True
            quote = char
        elif char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return index
        index += 1
    return -1


def _parse_numeric_literal(text: str) -> int | None:
    value = text.strip()
    value = re.sub(r"(?i)(ui64|i64|ull|llu|ll|ul|lu|u|l)$", "", value)
    value = value.strip()
    try:
        if value.lower().startswith("-0x"):
            return -int(value[3:], 16)
        return int(value, 0)
    except ValueError:
        return None
