from __future__ import annotations

from ida_pseudoforge.core.plan_schema import CleanPlan, FunctionCapture
from ida_pseudoforge.core.render_flow import format_flow_case_value
from ida_pseudoforge.core.render_labels import (
    semantic_label_display,
    semantic_label_map,
    semantic_label_name,
)
from ida_pseudoforge.core.render_status import _has_status_accumulator
from ida_pseudoforge.core.render_warnings import format_warning


def render_header_lines(
    capture: FunctionCapture,
    plan: CleanPlan,
    rename_map: dict[str, str],
    display_warnings: list[object],
    native_switch_dispatchers: set[str],
    version: str,
) -> list[str]:
    header = [
        "/*",
        "    Generated by PseudoForge.",
        f"    Version: {version}",
        "    Preview/export only. IDB was not modified.",
        f"    Function: {capture.name}",
        f"    Fingerprint: {plan.input_fingerprint}",
        f"    Rename candidates: {len(rename_map)}",
        f"    Flow rewrites: {len(plan.flow_rewrites)}",
        f"    Kernel semantic rewrites: {kernel_semantic_rewrite_count(plan)}",
        f"    Warnings: {len(display_warnings)}",
    ]

    if plan.flow_rewrites:
        for flow in plan.flow_rewrites:
            cases = ", ".join(format_flow_case_value(flow, value) for value in flow.recovered_cases[:64])
            if len(flow.recovered_cases) > 64:
                cases += ", ..."
            source_suffix = ""
            if flow.dispatcher in native_switch_dispatchers:
                source_suffix = " source=native_switch outline=suppressed"
            header.append(
                f"    Flow: {flow.kind} dispatcher={flow.dispatcher} cases=[{cases}] "
                f"confidence={flow.confidence:.2f}{source_suffix}"
            )

    if plan.comments:
        header.append("    Kernel insights:")
        for comment in plan.comments[:16]:
            kind = _ascii_comment_text(str(comment.get("kind", "kernel")))
            confidence = float(comment.get("confidence", 0.0))
            text_value = _ascii_comment_text(str(comment.get("text", "")))
            header.append(f"      - {kind}: {text_value} confidence={confidence:.2f}")

    if plan.cleanup_labels:
        header.append("    Label roles:")
        labels = semantic_label_map(plan)
        for label in plan.cleanup_labels[:16]:
            display_label = semantic_label_display(label.label, label.classification, labels)
            evidence = _ascii_comment_text(label.evidence)
            header.append(
                f"      - {display_label}: {label.classification} confidence={label.confidence:.2f} "
                f"({evidence})"
            )

    if display_warnings:
        header.append("    Warning detail:")
        for warning in display_warnings[:8]:
            header.append(f"      - {format_warning(warning)}")
        if len(display_warnings) > 8:
            header.append(f"      - ... {len(display_warnings) - 8} more warning(s)")

    if rename_map:
        rename_items = {item.old: item for item in plan.renames if item.apply}
        pairs = ", ".join(
            f"{old}->{item.new}({item.confidence:.2f},{item.source})"
            for old, item in sorted(rename_items.items())
        )
        header.append(f"    Renames: {pairs}")

    header.append("*/")
    return header


def kernel_semantic_rewrite_count(plan: CleanPlan) -> int:
    count = 0
    rewrite_comment_kinds = {
        "callback_registration",
        "critical_region",
        "device_extension_layout",
        "driver_dispatch_table",
        "driver_entry",
        "inferred_record_layout",
        "list_entry_insert_tail",
        "list_entry_unlink",
        "memory_manager_probe",
        "pool_tag",
        "registry_callback_registration",
        "zw_api_probe",
    }
    for comment in plan.comments:
        if str(comment.get("kind", "")) in rewrite_comment_kinds:
            count += 1
    count += len([label for label in plan.cleanup_labels if semantic_label_name(label.classification)])
    if _has_status_accumulator(plan):
        count += 1
    return count


def _ascii_comment_text(text: str) -> str:
    return text.encode("ascii", "backslashreplace").decode("ascii")
