/*
    Generated by PseudoForge.
    Version: <VERSION>
    Preview/export only. IDB was not modified.
    Function: sub_1400013F0
    Fingerprint: <FINGERPRINT>
    Rename candidates: 8
    Flow rewrites: 1
    Kernel semantic rewrites: 0
    Warnings: 0
    Flow: switch_recovery dispatcher=ioControlCode cases=[0x83376004, 0x8337A008, 0x8337E00C, 0x8337E010] confidence=0.57 source=native_switch outline=suppressed
    Renames: MasterIrp->systemBuffer(0.90,llm), a1->deviceObject(0.99,prototype), a2->irp(0.99,prototype), v10->ioStackLocation(0.94,kernel-irp-stack), v4->deviceExtension(0.94,kernel-driver-dispatch), v5->outputBufferLength(0.94,kernel-irp-stack), v6->inputBufferLength(0.94,kernel-irp-stack), v9->ioControlCode(0.94,kernel-irp-stack)
*/

/*
    PseudoForge normalized original pseudocode.
*/


NTSTATUS __fastcall sub_1400013F0(
        PDEVICE_OBJECT deviceObject,
        PIRP irp)
{
  NTSTATUS status; // [rsp+30h] [rbp-58h]
  __int64 deviceExtension; // [rsp+38h] [rbp-50h]
  ULONG outputBufferLength; // [rsp+44h] [rbp-44h]
  ULONG inputBufferLength; // [rsp+48h] [rbp-40h]
  PVOID systemBuffer; // [rsp+58h] [rbp-30h]
  ULONG ioControlCode; // [rsp+60h] [rbp-28h]
  PIO_STACK_LOCATION ioStackLocation; // [rsp+68h] [rbp-20h]

  deviceExtension = deviceObject->DeviceExtension;
  ioStackLocation = (PIO_STACK_LOCATION)sub_140003B30(irp);
  systemBuffer = irp->AssociatedIrp.SystemBuffer;
  inputBufferLength = ioStackLocation->Parameters.DeviceIoControl.InputBufferLength;
  outputBufferLength = ioStackLocation->Parameters.DeviceIoControl.OutputBufferLength;
  ioControlCode = ioStackLocation->Parameters.DeviceIoControl.IoControlCode;
  switch ( ioControlCode )
  {
    case 0x83376004: // CTL_CODE(0x8337, 0x801, METHOD_BUFFERED, FILE_READ_ACCESS)
      status = STATUS_SUCCESS;
      break;
    case 0x8337A008: // CTL_CODE(0x8337, 0x802, METHOD_BUFFERED, FILE_WRITE_ACCESS)
      status = STATUS_SUCCESS;
      break;
    case 0x8337E00C: // CTL_CODE(0x8337, 0x803, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
      status = STATUS_SUCCESS;
      break;
    case 0x8337E010: // CTL_CODE(0x8337, 0x804, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
      status = STATUS_SUCCESS;
      break;
    default:
      status = STATUS_INVALID_DEVICE_REQUEST;
      break;
  }
  switch ( status )
  {
    case 0x83376004:
      status = 1;
      break;
  }
  irp->IoStatus.Status = status;
  IofCompleteRequest(irp, 0);
  return status;
}

/*
    PseudoForge recovered switch view.
    Auxiliary dispatcher outline; review with the normalized original pseudocode above.
*/

/*
    Generated by PseudoForge.
    Version: <VERSION>
    This outline shows recovered dispatcher case values and conservative case bodies.
    Only single-statement returns and complete local branch slices are expanded here; complex bodies remain in the normalized original pseudocode.
    Native switch bodies already present in the normalized original are not duplicated here.
*/

// Native switch (ioControlCode) already exists in the normalized original pseudocode.
// Auxiliary outline suppressed to avoid duplicating incomplete case bodies.
