/*
    Generated by PseudoForge.
    Version: <VERSION>
    Preview/export only. IDB was not modified.
    Function: NtSetSystemInformation
    Fingerprint: <FINGERPRINT>
    Rename candidates: 9
    Flow rewrites: 1
    Kernel semantic rewrites: 1
    Warnings: 1
    Flow: switch_recovery dispatcher=infoClass cases=[9, 113, 194, 235, 243] confidence=0.60
    Kernel insights:
      - object_reference: Kernel object/context reference ownership changes are present confidence=0.84
    Label roles:
      - LABEL_214: dereference_object_and_return confidence=0.93 (Dereferences an object reference and returns status)
      - LABEL_421: cleanup_captured_unicode_string_and_return confidence=0.94 (Calls VfFreeCapturedUnicodeString and returns from the function)
    Warning detail:
      - Deterministic rule emission rejected: builtin.pattern.previous_mode_assignment: rename conflict on PreviousMode won by builtin.local.previous_mode_name
    Renames: Object->referencedObject(0.92,semantic-rule), PreviousMode->previousMode(0.99,semantic-rule), a1->systemInformationClass(0.99,prototype), a2->systemInformation(0.99,prototype), a3->systemInformationLength(0.99,prototype), updated->status(0.95,semantic-rule), v3->inputLength(0.93,pattern), v4->systemInfo128(0.90,pattern), v5->infoClass(0.97,pattern)
*/

/*
    PseudoForge normalized original pseudocode.
*/


NTSTATUS NTAPI NtSetSystemInformation(
        SYSTEM_INFORMATION_CLASS systemInformationClass,
        PVOID systemInformation,
        ULONG systemInformationLength)
{
  size_t inputLength;
  __m128i *systemInfo128;
  int infoClass;
  KPROCESSOR_MODE previousMode;
  NTSTATUS status;
  PVOID referencedObject;

  inputLength = (unsigned int)systemInformationLength;
  systemInfo128 = (__m128i *)systemInformation;
  infoClass = (int)systemInformationClass;
  previousMode = KeGetCurrentThread()->PreviousMode;
  status = STATUS_SUCCESS;
  if ( infoClass > SystemCpuQuotaInformation )
  {
    if ( infoClass == SystemSecureDumpEncryptionInformation )
    {
      return IoProvisionCrashDumpKey();
    }
    v115 = infoClass - SystemHypervisorBootPagesInformation;
    if ( !v115 )
    {
      return HvlQuerySetBootPagesInfo(systemInformation, 0LL);
    }
    v116 = infoClass - SystemTrustedAppsRuntimeInformation;
    if ( !v116 )
    {
      return STATUS_NOT_SUPPORTED;
    }
  }
  if ( infoClass == SystemFlagsInformation )
  {
    return STATUS_INFO_LENGTH_MISMATCH;
  }
LABEL_214:
  // PseudoForge: dereference_object_and_return confidence=0.93; Dereferences an object reference and returns status
  ObfDereferenceObject(referencedObject);
  return status;
LABEL_421:
  // PseudoForge: cleanup_captured_unicode_string_and_return confidence=0.94; Calls VfFreeCapturedUnicodeString and returns from the function
  VfFreeCapturedUnicodeString(systemInfo128);
  return status;
  return STATUS_INVALID_INFO_CLASS;
}

/*
    PseudoForge recovered switch view.
    Auxiliary dispatcher outline; review with the normalized original pseudocode above.
*/

/*
    Generated by PseudoForge.
    Version: <VERSION>
    This outline shows recovered dispatcher case values and conservative case bodies.
    Only single-statement returns and complete local branch slices are expanded here; complex bodies remain in the normalized original pseudocode.
    Native switch bodies already present in the normalized original are not duplicated here.
*/

switch (infoClass)
{
// SystemFlagsInformation
case 9:
{
    // PseudoForge: body_state=single_statement_body source_line=27.
    return STATUS_INFO_LENGTH_MISMATCH;
}
// SystemCpuQuotaInformation
case 113:
{
    // PseudoForge: body_state=complex_unsliced.
    // PseudoForge: complex body not structurally sliced; review normalized original pseudocode.
    break;
}
// SystemSecureDumpEncryptionInformation
case 194:
{
    // PseudoForge: body_state=single_statement_body source_line=18.
    return IoProvisionCrashDumpKey();
}
// SystemHypervisorBootPagesInformation
case 235:
{
    // PseudoForge: body_state=single_statement_body source_line=21.
    return HvlQuerySetBootPagesInfo(systemInformation, 0LL);
}
// SystemTrustedAppsRuntimeInformation
case 243:
{
    // PseudoForge: body_state=single_statement_body source_line=24.
    return STATUS_NOT_SUPPORTED;
}
default:
{
    // Original default/error path should be reviewed manually.
    break;
}
}
